base:
  language: c++
  engine: libFuzzer
  docker_image: ubuntu:latest
  deps:
    - run: DEBIAN_FRONTEND=noninteractive apt-get update
    - run: DEBIAN_FRONTEND=noninteractive apt-get install -y make autoconf bsdmainutils clang git libboost-system-dev libboost-filesystem-dev libboost-test-dev libc++1 libc++abi1 libc++abi-dev libc++-dev libclang1 libclang-dev libdb5.3++ libevent-dev libllvm-ocaml-dev libomp5 libomp-dev libqt5core5a libqt5dbus5 libqt5gui5 libtool llvm llvm-dev llvm-runtime pkg-config qttools5-dev qttools5-dev-tools software-properties-common
  steps:
    - run: ./autogen.sh
    - run: CC=clang CXX=clang++ ./configure --enable-fuzz --with-sanitizers=address,fuzzer,undefined --enable-danger-fuzz-link-all --disable-dependency-tracking
    - run: make -j8
    - run: find /temp_src/src/test/fuzz/* -not -name "fuzz" -not -name "addition_overflow" -not -name "addrdb" -not -name "addrman" -not -name "address_deserialize" -delete
